Test 7-base_geometry

==============================

Case Import
	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

====================================================================

Test Case 0

	>>> bg = BaseGeometry()
	>>> bg.integer_validator("data", [-4, 5, 3])
	Traceback (most recent call last):
		...
	TypeError: data must be an integer
	
	
	>>> bg.integer_validator("data", None)
	Traceback (most recent call last):
		...
	TypeError: data must be an integer
	
	
	>>> bg.integer_validator("data",)
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry.integer_validator() missing 1 required positional argument: 'value'
	
	>>> bg.integer_validator()
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry.integer_validator() missing 2 required positional arguments: 'name' and 'value'

=================================================================================

Test Case 1

	>>> bg.area()
	Traceback (most recent call last):
		...
	Exception: area() is not implemented
	
	Passing one argument to area method
	
	
	>>> bg = BaseGeometry()
	>>> bg.area(7)
	Traceback (most recent call last):
		      ...
	TypeError: BaseGeometry.area() takes 1 positional argument but 2 were given

====================================================================================

Test Case 2

	Passing dict to method
	>>> bg = BaseGeometry()
	>>> bg.integer_validator("age", {3, 4})
	Traceback (most recent call last):
	          ...
	TypeError: age must be an integer

===============================================================================

Test Case 3

	>>> bg.integer_validator("bool", false)
	Traceback (most recent call last):
	NameError: name 'false' is not defined

========================================================================================

Test Case 4

	>>> bg.integer_validator("data", True)
	Traceback (most recent call last):
	...
	TypeError: data must be an integer
	
========================================================================================

Test Case 5

	>>> bg.integer_validator("data", 1, 20)
	Traceback (most recent call last):
		...
	TypeError: BaseGeometry.integer_validator() takes 3 positional arguments but 4 were given

========================================================================================

Test Case 6

	>>> bg = BaseGeometry()
	>>> bg.integer_validator("my_int", 12)
	>>> bg.integer_validator("width", 89)
	
	>>> bg.integer_validator("name", "5")
	Traceback (most recent call last):
		      ...
	TypeError: name must be an integer
	>>> bg.integer_validator("name", "John")
	Traceback (most recent call last):
	...
	TypeError: name must be an integer
	
	>>> bg.integer_validator("age", 0)
	Traceback (most recent call last):
	...
	ValueError: age must be greater than 0
	
	>>> bg.integer_validator("distance", -4)
	Traceback (most recent call last):
	...
	ValueError: distance must be greater than 0
